{% set name = "lovelyplots" %}
{% set version = "0.0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LovelyPlots-{{ version }}.tar.gz
  sha256: 5fdfb794457c5fdfba7ccdcbac475e4b08ce9ac05b457cb53a2a959c100f02b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - matplotlib-base
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - python >=3.6

test:
  imports:
    - LovelyPlots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/killiansheriff/LovelyPlots
  summary: Format Matplotlib Plots for thesis, scientific papers and reports.
  license: MIT
  license_file:
    - LICENCE

extra:
  recipe-maintainers:
    - thewchan
