{% set name = "lovelyplots" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6b6e6cb50975e6681755b55447402e6cca6c21451adf6d1255884fd457739d68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - matplotlib-base
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - python >={{ python_min }}

test:
  imports:
    - lovelyplots
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/killiansheriff/LovelyPlots
  summary: Format Matplotlib Plots for thesis, scientific papers and reports.
  license: MIT
  license_file:
    - LICENCE

extra:
  recipe-maintainers:
    - thewchan
